### ISSUE TITLE
RBF层的固定问题

### ISSUE THREAD

**Issue by LeeeSe** [xinpingwang/paper-with-code#1]
若RBF不固定，那么给予初始权重还有什么意义呢？

**Comment by xinpingwang** [comment]
1. **论文中 RBF 层的参数是不可变的**
论文采用的是最大似然估计损失函数，结合 RBF 层输出值的计算方式，可知模型训练的目标是使得 F6 的输出和 RBF 中的某一组参数非常接近（这组参数代表的数字就是最终模型的预测结果）。如果让 RBF 层的参数变成可变的，那么模型训练后存在一种完全不能接受的情况，即：所有的 RBF 参数向量都一致，F6 的输出成为一个固定值，并且等于该参数向量，即：模型完全忽略输入，RBF 输出永远为 0。
2. **初始权重的意义**
在深度学习或者机器学习中，我们完成模型设计后，紧接着就是模型的训练，这时候我们一般会选择某种权重初始化方式（例如：随机，正态分布等）对模型中的参数进行初始化。初始化的目标不仅仅是为了让模型中的参数有一个初始值，更是为了让模型处在一个比较好训练的位置，这样优化算法可以使得模型更块的收敛。如果 RBF 的参数是可训练的，那么显而易见，这个设计好的初始权重会比随机初始化得到的一组值能让模型处在一个更好的训练位置。

> 在深度学习或者说机器学习中，我们设计模型一般来说都有两个目标：1. 端到端，2. 所有参数可训练。以论文的主题手写字符识别为例来说，手写字毕竟不同与打印字，我们选择的权重并不一定是最适合与数据集的，抛开上面说的最坏的情况，如果 RBF 参数可训练，也可能可以训练出一组最适合该数据集的权重；另外，如果看一些更新的模型，几乎看不到 RBF 这种设计了，更多的是 softmax。
